name: Executar a cada hora

on:
  push:
  schedule:
    - cron: '0 * * * *' # executa no minuto 0 de cada hora 
  workflow_dispatch: # permite também execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Rodar script ou comando
        run: echo "Executando workflow agendado!"
